### ISSUE TITLE
Double scroll bar

### ISSUE THREAD

**Issue by MortenHofft** [VtEcostudies/VAL_GBIF_Wordpress#11]
The double scrollbar is really annoying. I'm not quite sure how to solve it honestly, but I will look into it. 
If you want to get rid of it now, then the only option is to remove the footer on the data exploration page.

**Comment by jloomisVCE** [comment]
I agree it's annoying. I think I won't convince my colleagues to remove headers and footers - we want to capture this data widget in our context. What if we allocate a specific height for the widget's list views (table, gallery, datasets) and include that without scrollbars? Each view would need to have paging like ?view=TABLE does.

Hm... DATASETS doesn't seem to page over all results, it has just one long list?

**Comment by MortenHofft** [comment]
The header could stay, but the footer is causing the issue. Or rather the issue is the widget, but it can be fixed be removing the footer on the data exploration page. But I fully agree it isn't a good solution

**Comment by MortenHofft** [comment]
I've changed the widget slightly. But you still need to provide a size. 
It is currently set to `height: calc(100vh - 59px);`
I would suggest setting it to `min-height: calc(100vh - 59px);` instead. Perhaps making it dependent on device size?
The challenge is that the map (and the table) views need to know how much space they should take. And without specifying a height they will just collapse.

**Comment by MortenHofft** [comment]
I notice that the header is 80px high. So `min-height: calc(100vh - 80px);` is probably a better option. Then at least the user can scroll down and still see the whole data explorer.

**Comment by jloomisVCE** [comment]
Thanks. I was able to remove the footer (commenting inline php in html doesn't work, so i just removed that) finally. I don's see how that helps - the data-widget scrollbar remains and its size is still the min-height, I think .

I also tried the above style suggestion for the data-widget.

**Comment by MortenHofft** [comment]
When I use the site and change the styling I see a difference

<img width="1489" alt="before" src="https://user-images.githubusercontent.com/6759267/188870111-961c6594-748e-49bd-aec9-88ab84a29c35.png">
<img width="1653" alt="after" src="https://user-images.githubusercontent.com/6759267/188870118-ff99937f-2b15-40ee-b5f9-8399457bdbe6.png">

**Comment by jloomisVCE** [comment]
I was trying to alter style with .css sheets wihout success. I didn't notice the style key in the javascript React element's definition until just recently. I think it's working now.
