### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by MortenHofft** [VtEcostudies/VAL_GBIF_Wordpress#2]
On [the hoemepage](https://val.vtecostudies.org/)
There is a card that reads "Vermont Atlas of Life on iNaturalist Suprasses Half a Million Research-Grade Records" but it takes you to a 404

**Comment by jloomisVCE** [comment]
Thank you for pointing this out!

**Comment by jloomisVCE** [comment]
This was fixed by @kpmcfarland. Thanks again for finding this error.

https://val.vtecostudies.org/newsfeed/vermont-atlas-of-life-on-inaturalist-suprasses-half-a-million-research-grade-records/
