### ISSUE TITLE
State province filter

### ISSUE THREAD

**Issue by MortenHofft** [VtEcostudies/VAL_GBIF_Wordpress#4]
Since the state province filter is part of the root filter it probably makes little sense to add it
you can exclude filters - there might also be other filters you wish to exclude (e.g. `hosting organisation` ?). Anyway: do not feel obliged to keep filters around if you do not think they make sense for your audience. It might just be confusing instead.

https://hp-theme.gbif-staging.org/data-exploration-config#excluded-filters

**Comment by jloomisVCE** [comment]
Agreed. Thanks for the suggestion. I removed it.
