### ISSUE TITLE
missing maptilerKey

### ISSUE THREAD

**Issue by MortenHofft** [VtEcostudies/VAL_GBIF_Wordpress#5]
I notice that you have fiddled more with the configuration on the [hosted portal](https://github.com/gbif/hp-vtatlasoflife/blob/master/_includes/js/config.js#L84) than on https://val.vtecostudies.org/gbif-explorer/?view=MAP

Might make sense to repeat that? Personally I like the satellite view and your choice of the "Nature basemap"

**Comment by jloomisVCE** [comment]
Thanks for this hint! I thought This was a bug: I'd put apiKeys = {} and maps = {} inside the occurrence object. I fixed that and it looks like the hosted portal now.
