### ISSUE TITLE
Staging environment urls

### ISSUE THREAD

**Issue by MortenHofft** [VtEcostudies/VAL_GBIF_Wordpress#9]
The libraries and links used are set to staging. You should be using production instead.
https://github.com/VtEcostudies/VAL_GBIF_Wordpress/blob/0bcc8842bafedda94a31af186e590a535d4465fc/page-data-explorer-2022.php#L17

change
`https://react-components.gbif-staging.org/lib/gbif-react-components.js`
to
`https://react-components.gbif.org/lib/gbif-react-components.js`

**Comment by jloomisVCE** [comment]
Looks good.
